schemaVersion: 2.2.0
metadata:
  name: base
  version: 1.0.0
parent:
  uri: ./base.devfile.yaml
  components:
    - name: runtime
      container:
        image: python:3.11  # arbitrary
      attributes:
        pod-overrides:
          spec:
            imagePullSecrets:
              - name: abcd